relm4-examples/examples/to_do.rs

let the area of the todo list expand vertical

improve todo list example

---

relm4-components/Cargo.toml
relm4-components/src/alert.rs
relm4-components/src/open_button/mod.rs
relm4-components/src/open_dialog.rs
relm4-components/src/save_dialog.rs
relm4-examples/examples/open_button.rs
relm4-examples/examples/save_dialog.rs
src/lib.rs

Add ability to reuse same component multiple times in the same view

---

relm4-examples/examples/tracker.rs

It now uses an iterator to select icons in random

examples: make tracker example more idiomatic

---

relm4-examples/examples/entry.rs
relm4-examples/examples/stack.rs

add new entry example

---

src/app.rs

do not pass CLI arguments to GTK by default

---

.github/workflows/rust.yml
src/traits/mod.rs

While working on another change I noticed that this test was failing. It wasn't caught because it doesn't run in CI.

fix doctest and run tests in CI

---

src/factory/widgets/adwaita.rs

Added the implementations of the traits 'FactoryView' and 'FactoryListView' for adwaitas Leaflet type

Implemented FactoryView and FactoryListView for Leaflet

---

examples/simple_manual.rs
src/app.rs
src/lib.rs

RelmApp makes it convenient to use components as the root of the app.
WIP because I haven't tested it yet in examples.

Reintroduce RelmApp

---

examples/simple_manual.rs
src/app.rs
src/component/elm_like.rs
src/component/mod.rs
src/lib.rs

Adds a simpler component trait that implements the normal component trait. This should help reducing the complexity for simple components.
Requires #96  to be merged before.
@mmstick can you review?

Simple component

---

relm4-examples/libadwaita/examples/calc-trainer.rs

a small change which makes the UI of the calc-trainer a little more appealing.

small imrpovement on calc-trainer UI

---

.github/workflows/rust.yml

Would be nice to automate this :)

check formatting in CI

---

examples/progress.rs
examples/settings_list.rs
relm4/src/component/builder.rs
relm4/src/component/sender.rs
relm4/src/component/traits.rs

refactor!: Launch commands from ComponentSender, removing type Command from trait

---

examples/factory.rs
examples/grid_factory.rs
examples/libadwaita/tab_factory.rs
relm4/src/factory/mod.rs
relm4/src/factory/widgets/gtk.rs
relm4/src/factory/widgets/libadwaita.rs
relm4/src/factory/widgets/mod.rs
relm4/src/factory/widgets/tests.rs

- Add `FactoryView` impl for `gtk::FlowBox`.
- Add tests for different widgets that impl `FactoryView`.
- Fix bugs related to the usage of `gtk::ListBoxRow` as the child inside `gtk::ListBox`.
- Fix bugs related to child ordering.
- Fix bugs related to invalid indexes.
- Minor changes in docs and examples.

Factory improvements

---

relm4-examples/libadwaita/examples/sudoku_solver.rs

not sure if it still makes sense to improve it in main, or if it makes more sense to port it to the new way…

fix layout of sudoku example

---

relm4/Cargo.toml
relm4/src/factory/widgets/libpanel.rs
relm4/src/factory/widgets/mod.rs
relm4/src/lib.rs

Adding back a feature that was removed.

0.5: implement factory trait for libpanel Paned

---

relm4/src/component/mod.rs

Implement OnDestroy using ObjectExt

---

relm4/src/app.rs
relm4/src/lib.rs

Reintroduce RelmApp::with_app

---

relm4/src/factory/mod.rs

Implement `clear` method for `FactoryVecDeque`

---

relm4/src/app.rs

Handle subclassing in `RelmApp::with_app`

---

relm4/src/channel.rs
relm4/src/component/controller.rs
relm4/src/factory/traits.rs
relm4/src/lib.rs
relm4/src/shared_state.rs

Shared state

---

examples/simple.rs
relm4/src/app.rs

ApplicationWindow does some things automatically but requires a certain initialization order. This PR improves the order in which things are initialized.

Improve RelmApp startup for ApplicationWindow

---

README.md

Added my relm4/libadwaita project to the list!

Add NixOS Configuration Editor to project list

---

examples/libadwaita/tab_game.rs
relm4/src/factory/collections/vec_deque.rs

It's not perfect, but maybe a little bit better. What do you think?

core: Add method to drop factory guard

---

relm4/Cargo.toml
relm4/benches/stress_test.rs

@cofee-on-the-desk this was my testing setup. As I said, there were no measurable differences.

Add stress test benchmark

---

relm4/src/factory/widgets/libadwaita.rs

Needed this for my project, wanted everybody to have it 😸

Implemented ExpanderRow

---

examples/Cargo.toml
examples/drawing.rs
examples/to_do.rs

Port drawing example to 0.5

---

Cargo.toml
relm4-components/src/alert.rs
relm4-macros/tests/ui/compile-fail/component-empty.stderr

re-enable relm4-components

---

relm4/src/factory/widgets/libadwaita.rs

Implement Factory for adw Carousel

---

.github/workflows/rust.yml
CHANGES.md
examples/message_broker.rs
relm4/src/component/builder.rs
relm4/src/component/message_broker.rs
relm4/src/component/mod.rs
relm4/src/component/traits.rs
relm4/src/lib.rs

Fixes #213 
@Paveloom what do you think? Do you want to review this PR?

core: Add message broker

---

.github/workflows/rust.yml
examples/menu.rs

Use clippy for examples and deny warnings in CI

examples: Check with clippy in CI

---

relm4-macros/src/visitors.rs
rustfmt.toml

Add some basic rules and enable more as soon as they become stable.

Add basic rustfmt config

---

.github/workflows/rust.yml
examples/macro_reference.rs

examples: Add optional assign to macro_reference

---

CHANGES.md
relm4/src/extensions/container.rs

core: More RelmContainerExt impls for adw

---

.github/workflows/rust.yml
CHANGES.md
README.md
relm4-macros/Cargo.toml
relm4/Cargo.toml

all: Bump MSRV to 1.63

---

examples/relm4-components/Cargo.toml
examples/relm4-components/alert.rs

Port the `alert` example to 0.5 syntax. cc #100.

port alert example to 0.5

---

CHANGES.md
relm4/src/extensions/container.rs
relm4/src/extensions/mod.rs
relm4/src/extensions/remove.rs
relm4/src/factory/widgets/libadwaita.rs

core: Impl more traits for adw::PreferencesGroup

---

CHANGES.md
relm4/src/factory/component_storage.rs
relm4/src/factory/data_guard.rs
relm4/src/factory/handle.rs
relm4/src/factory/traits.rs

core: Remove Debug requirement for FactoryComponent

---

CHANGES.md
relm4/src/factory/collections/vec_deque.rs

core: Add iter_mut to FactoryVecDeque

---

relm4-components/src/simple_combo_box.rs

components: Optional selection in SimpleComboBox

---

CHANGES.md
relm4-macros/src/widgets/gen/destructure_fields.rs
relm4-macros/src/widgets/gen/return_fields.rs
relm4-macros/src/widgets/gen/struct_fields.rs
relm4-macros/src/widgets/gen/util/has_struct_field.rs
relm4-macros/src/widgets/gen/util/mod.rs
relm4-macros/src/widgets/mod.rs
relm4-macros/src/widgets/parse/top_level_widget.rs
relm4-macros/src/widgets/parse/widget.rs
relm4-macros/tests/ui/compile-fail/dead_code.rs
relm4-macros/tests/ui/compile-fail/dead_code.stderr

macros: Don't generate dead code in widgets struct

---

CHANGES.md
examples/libadwaita/tab_game.rs
relm4-components/src/simple_combo_box.rs
relm4/src/shared_state.rs

core: Improve SharedState

---

.github/workflows/rust.yml
CHANGES.md
Cargo.toml
relm4-components/Cargo.toml

Backport to fix https://github.com/Relm4/Relm4/issues/292

Fixed builds on docs.rs and bumped version

---

relm4/Cargo.toml

Update criterion to 0.4

---

CHANGES.md
relm4-macros/src/lib.rs
relm4-macros/src/token_streams.rs
relm4-macros/src/widgets/gen/util/property_name.rs
relm4-macros/src/widgets/mod.rs
relm4-macros/src/widgets/parse/property.rs
relm4-macros/src/widgets/span/property_name.rs
relm4-macros/tests/local_ref_container.rs

Fixes #303 (and improves the error reporting a little bit)

macros: Fix codegen for RelmContainerExt

---

relm4-macros/src/component/inject_view_code.rs
relm4-macros/src/widgets/gen/init.rs
relm4-macros/src/widgets/gen/util/widget_func.rs

Small improvements for the macros.

macros: Slightly improve code and code generation

---

relm4/Cargo.toml

Updated the fragile dependency to the newest major version

Update fragile dependency to 2.0.0

---

CHANGES.md
README.md
relm4-components/Cargo.toml
relm4-macros/Cargo.toml
relm4/Cargo.toml

Steps for releasing a this version:
1. Merge this PR
2. `git pull origin main`
3. `cd relm4-macros` and `cargo publish`
4. `cd ../relm4` and `cargo publish`
5. `cd ../relm4-components` and `cargo publish`
6. :tada: :tada: :tada:

all: Bump version to 0.5.0-beta.4

---

.github/workflows/rust.yml
CHANGES.md
relm4-macros/src/lib.rs
relm4/Cargo.toml
relm4/src/lib.rs

> The first commit should cause the CI to fail, it is just a test to verify that the current version fails to build

all: Add CI job to check docs

---

CHANGES.md
README.md
relm4/Cargo.toml

core: Add feature flags for GNOME SDK versions

---

CHANGES.md
relm4/src/extensions/container.rs
relm4/src/extensions/mod.rs
relm4/src/extensions/set_child.rs

core: Impl RelmContainerExt for adw::Squeezer

---

CHANGES.md
relm4-macros/src/widgets/gen/util/widget_func.rs
relm4-macros/src/widgets/mod.rs
relm4-macros/tests/complex_func_path.rs

@roosemberth this should fix your problem, feel free to leave a review :)

Fix type parsing

---

CHANGES.md
relm4/src/factory/widgets/libadwaita.rs

add factory for adw::PreferencePage

---

relm4/src/factory/sync/collections/vec_deque.rs

add from_vec method to FactoryVecDeque type

---

CHANGES.md
relm4/src/shared_state/state.rs

core: Add non-blocking methods to SharedState

---

relm4/src/factory/sync/collections/vec_deque.rs
relm4/src/factory/sync/traits.rs

Sashinexists factoryvecdeque cloning

---

CHANGES.md
examples/grid_factory.rs
relm4/src/factory/async/traits.rs
relm4/src/factory/sync/collections/vec_deque.rs
relm4/src/factory/widgets/traits.rs

core: Pass &self to Position::position()

---

CHANGES.md
README.md
relm4-components/Cargo.toml
relm4-macros/Cargo.toml
relm4/Cargo.toml

Bump versions and tag commit in preparation of publishing.

all: Bump version to 0.5.0-rc.1

---

examples/README.md

The repository is named with a capital, update the instructions to match

Correct command in example README

---

CHANGES.md
relm4-macros/src/widget_template.rs
relm4-macros/src/widgets/gen/init.rs
relm4-macros/tests/widget_template.rs

macros: Support widget templates as roots of components

---

CHANGES.md
examples/factory.rs
examples/factory_async.rs
relm4/src/app.rs
relm4/src/component/async/traits.rs
relm4/src/component/sync/traits.rs
relm4/src/factory/async/collections/vec_deque.rs
relm4/src/factory/async/traits.rs
relm4/src/factory/sync/collections/vec_deque.rs
relm4/src/factory/sync/traits.rs
relm4/src/runtime_util.rs
relm4/tests/drop_after_quit.rs
relm4/tests/shutdown_after_quit.rs

Fixes https://github.com/Relm4/relm4-template/issues/6

core: Fix factory shutdown on app shutdown

---

CHANGES.md
relm4/src/extensions/mod.rs
relm4/src/extensions/set_child.rs
relm4/src/lib.rs

core: Impl SetChildExt for Expander

---

relm4/src/runtime_util.rs

I've finally found the bug that froze my app! Amazing how much such a small number can change...

core: Fix freeze on app shutdown

---

CHANGES.md
relm4-macros/src/component/mod.rs
relm4-macros/src/factory/mod.rs
relm4-macros/src/token_streams.rs
relm4-macros/src/util.rs
relm4-macros/src/widgets/gen/assign/widgets.rs
relm4-macros/src/widgets/gen/util/widget_func.rs
relm4-macros/src/widgets/mod.rs
relm4-macros/tests/codegen_order.rs

Some fixes and a new test case. This is necessary for updating gtk-rs to 0.6.

macros: Several small fixes

---

.github/workflows/rust.yml
CHANGES.md
examples/components.rs
relm4-components/Cargo.toml
relm4-components/examples/web_image.rs
relm4-components/src/lib.rs
relm4-components/src/web_image.rs
relm4-macros/Cargo.toml
relm4-macros/src/lib.rs

components: Add web image component

---

CHANGES.md
relm4-macros/src/widgets/gen/init.rs
relm4-macros/tests/widget_template.rs

macros: Fix template children of root widgets

---

CHANGES.md
relm4/src/factory/widgets/libadwaita.rs

core: Impl FactoryView for Leaflet

---

CHANGES.md
examples/data_binding.rs
relm4/src/binding/bindings.rs
relm4/src/binding/mod.rs
relm4/src/binding/widgets.rs
relm4/src/extensions/object_ext.rs

core: Improve data bindings

---

CHANGES.md
examples/actions.rs
examples/menu.rs
relm4/src/actions/mod.rs

Should fix #431
@nahuelwexd what do you think? I think the new `register_for_main_application` method should work for you.

Improve actions API

---

CHANGES.md
relm4/src/extensions/widget_ext.rs

Add method to set tooltip

---

README.md

Adds Rhino Setup to the list of projects using Relm4

docs(readme): add `rhino-setup`

---

.gitignore

It's pretty straight forward...

Ignoring Jetbrains IDE stuff

---

CHANGES.md
relm4-components/Cargo.toml
relm4/Cargo.toml
relm4/src/app.rs

core: Fix multiple app instances

---

CHANGES.md
relm4-macros/src/widgets/parse/view_widgets.rs

Addresses the most important issue in #469

macros: Allow trailing commas in view

---

CHANGES.md
relm4-macros/src/widgets/gen/assign/assign_property.rs
relm4-macros/src/widgets/gen/assign/conditional_widget.rs
relm4-macros/src/widgets/gen/assign/mod.rs
relm4-macros/src/widgets/gen/assign/signal_handler.rs
relm4-macros/src/widgets/gen/assign/widgets.rs
relm4-macros/src/widgets/gen/conditional_init.rs
relm4-macros/src/widgets/gen/init.rs
relm4-macros/src/widgets/gen/update_view.rs
relm4-macros/src/widgets/gen/util/mod.rs
relm4-macros/src/widgets/gen/util/property_name.rs
relm4-macros/src/widgets/gen/util/widget.rs
relm4-macros/tests/widget_template.rs

macros: Fix for multiple template children instances

---

relm4/src/extensions/widget_ext.rs

This adds two simple convenience methods to the `RelmWidgetExt` trait with their implementation for `gtk::Widget`.

Add `set_margin_vertical`/`horizontal` to `RelmWidgetExt`

---

CHANGES.md
relm4-macros/src/widgets/gen/update_view.rs
relm4-macros/tests/widget_template.rs

#527 
@eminfedar can you check whether this fixes the issue?

macros: Fix track attribute for template children

---

CHANGES.md
relm4/src/component/async/connector.rs
relm4/src/component/async/mod.rs
relm4/src/component/async/stream.rs
relm4/src/component/mod.rs

core: Add `AsyncComponentStream`

---

relm4-components/examples/combo_box.rs

Show how to access variants when the combo box is already launched

---

relm4/src/prelude.rs

Export async types in prelude. Closes #386

---

README.md

Score Tracker is an application for tracking player scores in card and board games.
Thank you for creating this awesome crate, it is a huge improvement over writing an app using gtk-rs alone.

docs(readme): add score-tracker

---

CHANGES.md
relm4/src/app.rs
relm4/src/channel/mod.rs

core: Fix overriding the visibility of the main window

---

relm4-macros/src/widgets/gen/assign/assign_property.rs
relm4-macros/src/widgets/gen/conditional_init.rs
relm4-macros/src/widgets/gen/update_view.rs
relm4-macros/src/widgets/gen/util/if_branch.rs
relm4-macros/src/widgets/parse/conditional_widget.rs
relm4-macros/src/widgets/parse/returned_widget.rs
relm4-macros/src/widgets/parse_util.rs
relm4/src/binding/bindings.rs

See #533 for more information.

Improve macro hygiene

---

CHANGES.md
examples/tracker.rs
relm4/src/app.rs
relm4/src/lib.rs

core: Move global methods into RelmApp

---

CHANGES.md
relm4/src/actions/mod.rs

core: Add new methods to RelmAction

---

CHANGES.md
relm4/src/component/async/builder.rs
relm4/src/component/sync/builder.rs
relm4/src/extensions/container.rs
relm4/src/extensions/mod.rs
relm4/src/extensions/remove.rs
relm4/src/extensions/set_child.rs

core: Add better support for adw v1_4 widgets

---

CHANGES.md
examples/typed_grid_view.rs
relm4/src/typed_view/grid.rs
relm4/src/typed_view/mod.rs

Typed wrapper implementation for gtk::GridView. Largely based on TypedListView.

Implement TypedGridView

---

CHANGES.md
relm4-macros/tests/ui/compile-fail/init-identifers.rs
relm4-macros/tests/ui/compile-fail/init-identifers.stderr
relm4-macros/tests/ui/compile-fail/no-view-output.rs
relm4-macros/tests/ui/compile-fail/no-view-output.stderr
relm4/src/component/async/builder.rs
relm4/src/component/sync/builder.rs
relm4/src/factory/data_guard.rs

Simpler rt

---

CHANGES.md
relm4/src/extensions/container.rs
relm4/src/extensions/mod.rs

core: Add extension traits for PreferencesPage

---

CHANGES.md
examples/components.rs

examples: Fix dialog in "components"

---

CHANGES.md
relm4/src/extensions/widget_ext.rs

core: Add expand and align methods to RelmWidgetExt

---

CHANGES.md
examples/multi_window.rs

examples: Add example for multiple windows

---

CHANGES.md
relm4/src/app.rs

This adds in functions that allow specification for the priority of CSS classes. I'm needing this as part of my work on #645.

Add functions to set priority of CSS stylesheets

---

relm4/src/app.rs
relm4/src/lib.rs

Part of the work for #645. As discussed in the Matrix dev room, feel free to not merge this until we look at how it's used in the PR for that (once I have it created).

Add global functions to set CSS

---

CHANGES.md
Cargo.toml
examples/components.rs
examples/leaflet_sidebar.rs
examples/message_broker.rs
examples/tracker.rs
relm4-components/Cargo.toml
relm4-components/src/alert/mod.rs
relm4-components/src/lib.rs
relm4-components/src/open_button/mod.rs
relm4-css/Cargo.toml
relm4-css/README.md
relm4-css/build.rs
relm4-css/src/lib.rs
relm4-macros/src/lib.rs
relm4/Cargo.toml
relm4/src/lib.rs

*This should be merged after #649, as it builds on top of changes made there.*
This adds in static definitions for styles and colors in the Adwaita stylesheet.

Add Adwaita style classes and colors

---

README.md

Add application that uses relm4 to read me.

Add project showcase Toolbox Tuner to README.md

---

README.md

Added Bitritter to Projects using Relm4

---

examples/drag_and_drop.rs

Added a example for showing how drag and drop works in Relm works.
I once asked how to do it and it was mentioned that there should be an example for it.
There are clippy warnings in relm4-macros that don't originate from me.

Add an example that shows drag and drop

---

CHANGES.md
relm4-components/src/open_button/mod.rs

components: Hide recent button from `OpenButton` component when there is no entries

---

CHANGES.md
relm4/src/prelude.rs

Add more async factory types to prelude

---

relm4-macros/src/widgets/gen/destructure_fields.rs

macros: add returned widget to destructure-struct

---

CHANGES.md
examples/embedded_logo.rs

Add a example that shows embedded logo

Add a example that shows embedded logo

---

relm4-components/Cargo.toml
relm4-components/LICENSE-APACHE
relm4-components/LICENSE-MIT
relm4-css/Cargo.toml
relm4-css/LICENSE-APACHE
relm4-css/LICENSE-MIT
relm4-macros/Cargo.toml
relm4-macros/LICENSE-APACHE
relm4-macros/LICENSE-MIT
relm4/Cargo.toml
relm4/LICENSE-APACHE
relm4/LICENSE-MIT

- Update include to be from the base of Cargo.toml
- Add symlinks
- Resolves #655

Update Cargo.toml Configurations for LICENSE Files

---

examples/settings_list.rs
examples/simple.rs
examples/simple_async.rs
examples/simple_manual.rs
examples/tracker.rs

Harmonize namings in first examples

Harmonize simple examples

---

CHANGES.md
examples/factory_hash_map.rs
relm4/src/factory/sync/collections/hashmap.rs
relm4/src/factory/sync/collections/vec_deque.rs

core: Add factory methods for setting the active stack page

---

CHANGES.md
relm4/src/binding/widgets.rs

Impl the `Binding` trait for `gtk::CheckButton`.

Impl Binding for gtk::CheckButton

---

README.md

A trivial change to the README to add a project that employs Relm4. Kudos to all contributors of this library!

Reference Exercise Timer in README

---

README.md

I managed to create my first app with Relm4 and to publish it on Flathub.
There is still some things to do. But it's a lot of fun. Relm4 is really awesome!
Thank you everyone contributing to Relm4!!

add Words! to projects using Relm4

---

CHANGES.md
relm4-components/examples/open_button.rs
relm4-components/src/open_button/mod.rs

components: Add `icon` to `OpenButton`

---

README.md

Hi, my project has been using Relm4 for quite a while now, gradually moving over from plain gtk-rs. By now almost all of the UI uses Relm4, so I think it is fair to include it in the list.
Not applicable

Add LACT to list of projects using Relm4 in README

---

examples/tracker.rs
relm4-components/src/open_button/factory.rs

Fix clippy warnings after rand 0.9.0 update

---

examples/tracker.rs

Implement guaranteed icon uniqueness on refresh by adding regeneration validation.
Before this change, clicking the icon refresh button sometimes showed no visual change because the random generator could select the same icon consecutively.

tracker.rs: Avoid repeats icon. 

---

README.md

This PR lists xdg-mimer as an application whose development has truly been made much easier using Relm4.

Listing xdg-mimer as an app that is built on Relm4
