Cargo.toml
The GTK4 has been updated to 0.2, and [apparently](https://gtk-rs.org/gtk4-rs/git/book/prerequisites.html#cargo) a new way of specifying the package.
I haven't encountered any issues when issuing `cargo build` but haven't tested it on any projects.
=> Updated gtk4 to 0.2 and new declaration.

relm4-components/src/alert.rs, relm4-examples/examples/components.rs, relm4-examples/examples/macro_test.rs, src/util/widget_plus.rs
There is already `WidgetExt::{add_css_class, remove_css_class}` in GTK4.
=> Remove classname methods from WidgetPlus

src/factory/mod.rs
This reduces constraints on `Factory::Key` so implementing factory for
generic key becomes possible.
relm4-store-record `Id` is generic in terms of values which it holds.
It's user responsibility to provide values "good enough" for id to have
a meaning.
=> Make factory key unsized

Cargo.toml, src/lib.rs, src/micro_component.rs
Implementation of #49 
It's required to make #46 go forward
=> Micro components

relm4-macros/src/lib.rs
I tried writing a `manual_view` function in my `view!` macro like this:
```rust
fn manual_view(&self) {
let file = match &model.file {
Some(file) => file,
None => return,
};
match &file.preview {
FilePreview::Image(path) => {
self.image.set_file(Some(&path.to_string_lossy()));
}
FilePreview::Icon(icon) => {
self.image.set_gicon(Some(icon));
}
}
}
```
This led to some strange behavior in my application, where certain widgets were containing stale data. Expanding the macro revealed the problem:
```rust
/// Update the view to represent the updated model.
fn view(
&mut self,
model: &FilePreviewModel,
sender: ::relm4::Sender<<FilePreviewModel as ::relm4::Model>::Msg>,
) {
let file = match &model.file {
Some(file) => file,
None => return,
};
match &file.preview {
FilePreview::Image(path) => { …
```
=> wrap tokens from `manual_view` in an IIFE

src/lib.rs
This is useful for sending messages to components.
=> allow expressions in `send!` macro

src/component/bridge.rs, src/component/elm_like.rs, src/component/stateful.rs
- Makes the `Bridge::attach_to` method available for `StatefulComponent` types
- Permits components to have any type as the root widget, instead of just GTK widgets
- Adds `Bridge::preflight` for pre-launch configuration for everything else
=> Allow root widget to be any type

Cargo.toml, src/factory/collections/factory_vec.rs, src/lib.rs
`FactoryVec` was acting weird and all over the place for me and it might be #84, too. I had some fun and modeled its fields as a state machine. Brings `push`, `pop`, and `clear` in line with the described model and fixes the indexing problems in the `generate` method. I think it is (more) correct now, but one could probably be smarter about `clear` and the use of `Vec::remove`.
=> Fix FactoryVec state changes

examples/settings_list.rs, examples/simple_manual.rs, src/app.rs, src/component/builder/elm_like.rs, src/component/builder/mod.rs, src/component/builder/stateful.rs, src/component/connector.rs, src/component/elm_like.rs, src/component/mod.rs, src/component/state_watcher.rs, src/component/stateful.rs
Fixes #89 
---
| Old | New | Comment |
| - | - | - |
| **Types** |
| `Bridge` | `ComponentBuilder` |
| `Bridge::preflight` | `ComponentBuilder::update_root` |
| `Fuselage` | `ComponentParts` | I think it's nice to keep the struct because tuples are a bit weird to index and there is an API for accessing `ComponentParts`, similar to micro components |
| `Fairing` | `Connector` | Since connecting stuff is the main purpose of this type, I think this name makes sense |
| **Component trait** |
| `Component::dock` | `Component::init_parts` |
| `Payload` | `InitParams` | I like payload regardless of the analogy, but init params is still more expressive |
=> RFC: Rename component types

src/extensions/container.rs, src/extensions/mod.rs, src/extensions/removable.rs, src/extensions/set_child.rs
Adds `RelmSetChildExt` and `RelmRemovableExt` and uses `RelmSetChildExt` for several `RelmContainerExt` and `RelmRemovableExt` implementations.
=> Extend container extension traits

Cargo.toml, examples/progress.rs, examples/settings_list.rs, examples/simple.rs, examples/simple_manual.rs, relm4-macros/src/component/mod.rs, src/channel.rs, src/component/builder/elm_like.rs, src/component/builder/mod.rs, src/component/builder/stateful.rs, src/component/connector.rs, src/component/controller.rs, src/component/elm_like.rs, src/component/mod.rs, src/component/state_watcher.rs, src/component/stateful.rs, src/lib.rs, src/shutdown/attached.rs, src/shutdown/mod.rs, src/shutdown/receiver.rs, src/shutdown/sender.rs, src/worker.rs
The current component traits have a big problem with handling graceful shutdowns. This change adds a new method to the component traits — `shutdown()` — which allows a component to get one last chance to perform a cleanup routine before its terminated. It also hands a broadcast receiver to each spawned command so that they can be notified of a component shutdown.
=> 0.5: Graceful Shutdown

src/component/builder/mod.rs, src/component/connector.rs, src/worker.rs
I'm experimenting with the new components in my project. I often find myself cloning stuff, in two situations: 
```rust
// ... we have a 'window' variable defined somewhere before
let properties = {
let window = window.clone();
PropertyWindow::init()
.update_root(move |w| w.set_transient_for(Some(&window)))
.launch(())
.detach()
};
```
I have to clone the `window` here, as the closure takes ownership of it's arguments.
The new method `transient_to` can help remove this clone. I use 'to' here for the analogy to an existing method, `attach_to`.
```rust
let properties = PropertyWindow::init()
.transient_to(&window)
.launch(())
.detach();
```
```rust
let rules = {
let sender = sender.clone();
RuleViewModel::init()
.launch(data.current_dir_rules())
.forward(sender, move |msg| {
// .. forward …
```
=> Add a few improvements to reduce the amount of clone in user code

Cargo.toml, src/factory/widgets/mod.rs, src/factory/widgets/panel.rs, src/lib.rs
libpanel is still pretty unstable, so I'm not sure if we want to add any additional stability warnings here (we might want to upgrade the library in a non-semver compatible way).
=> implement factory traits for libpanel Paned

src/extensions/mod.rs, src/extensions/removable.rs
Introduce `RelmRemovableExt::remove_all` method, which would allow to remove all children from a widget. I think it could be useful.
I've had to change the trait implementation a bit, because otherwise you would have to specify the generic type parameter every time you use this method (like `RelmRemovableExt::<gtk::Widget>::remove_all(&container)`). The static type checking remains though.
If the implementation change is not acceptable for some reason, I can drop it and instead introduce a separate trait for this method.
=> Add `RelmRemovableExt::remove_all` and `RelmWidgetExt::iter_children_reverse`

Cargo.toml
This makes it possible to use the new `#[gtk::test]` macro which should help with writing tests.
=> Use gtk-rs from git

src/actions/mod.rs, src/actions/traits.rs
Minor breaking change to the action traits, but it makes implementing
them manually a bit less verbose. Maybe someday it will let us compute
the full action name at compile-time, too.
=> use associated consts for action names

src/extensions/mod.rs, src/extensions/removable.rs, src/extensions/tests.rs
1) Remove `RelmRemovableExt::remove_all`. It relies on widget internal structure and may break between releases, which would be hard to maintain.
2) Remove `RelmWidgetExt::iter_children`, `RelmWidgetExt::iter_children_reverse` and `RelmWidgetExt::for_each_children`. Those aren't really reliable and can yeild surprising results on some widgets, like `gtk::HeaderBar` (see [link](https://github.com/AaronErhardt/Relm4/issues/103#issuecomment-1029534362)).
3) Instead, introduce widget-specific extensions: `RelmBoxExt`, `RelmListBoxExt`, `RelmFlowBoxExt` and `RelmGridExt`. Add tests for those extensions.
GTK4 encourages widget-specific implementations, instead of generalizations. See [link](https://discourse.gnome.org/t/gtk4-widget-container-api-model/7672).
=> Drop general extensions in favor of widget-specific extensions

relm4-components/src/open_button/factory.rs, src/util/widget_plus.rs
Fix warning that occurs when you use `inline_css` without `;` at the end:
```rust
(process:108104): Gtk-WARNING **: 13:41:29.363: Theme parsing error: <data>:1:3-13: Expected ';' at end of block
```
A small API change - the method now requires `&str` instead of `&[u8]`.
=> Fix warning for `inline_css`, adjust API

src/app.rs
Libadwaita requires to be initialized after GTK.
Resolves #133
=> Initialize libadwaita after GTK

relm4/src/extensions/mod.rs, relm4/src/extensions/remove.rs
A small fix to make the trait name more intuitive.
=> Rename `RelmRemovableExt` to `RelmRemoveExt`

examples/factory.rs, examples/grid_factory.rs, examples/libadwaita/tab_factory.rs, examples/progress.rs, examples/settings_list.rs, examples/simple.rs, examples/simple_manual.rs, relm4-macros/src/component/mod.rs, relm4/src/component/builder.rs, relm4/src/component/mod.rs, relm4/src/component/sender.rs, relm4/src/component/traits.rs
This is an experiment to reduce boilerplate. Feedback would be appreciated if this seems like a good idea or not.
This will combine the two `input: Sender<Self::Input>, output: Sender<Self::Output>` parameters into a single `sender: ComponentSender<Self>`. This new sender type contains the two senders and also implements `fn input(&self, message: Self::Input)` and `fn output(&self, message: Self::Output)` for convenience. The `ComponentSender` is a type alias for an `Rc<ComponentSenderInner>` so it is clonable across signal callbacks.
This could also be extended to contain a command sender so that we could combine the `SimpleComponent` and `Component` traits back together.
=> refactor!: Combine senders into ComponentSender type

.github/workflows/rust.yml
This should be ported to the `next` branch as well, so that we can get CI runs on PRs to that branch. (The build is currently broken on that branch, but it will be helpful to see if there's any unintended breakage).
=> run CI on all branches

relm4/src/extensions/iter_children.rs, relm4/src/extensions/mod.rs, relm4/src/extensions/remove.rs, relm4/src/extensions/set_child.rs, relm4/src/extensions/tests.rs
- Add `ContainerChild` trait to define the type of container children. Previously this was inside `RelmRemovableExt`, which was fine but not all widgets that store children can actually remove them, for example `adw::TabView`. A few traits rely on this one to get the correct type of children.
- Add `RelmIterChildrenExt` impl for `adw::TabView`.
- Add `RelmRemoveAllExt` impl for T: `RelmSetChildExt`.
- Fix `RelmIterChildrenExt` impl for `gtk::Grid` (now relies on the widget position inside the grid to decide the right ordering).
- Move `RelmIterChildrenExt` to a separate module.
- Minor changes in tests
=> Improvements to extension traits

src/worker.rs
Presumably these types should have such a method, since `RelmComponent` does.
=> Add `sender()` methods to `RelmWorker` and `AsyncRelmWorker`

relm4-macros/src/widget_macro/mod.rs, relm4/src/channel.rs, relm4/src/component/connector.rs, relm4/src/component/controller.rs, relm4/src/component/state_watcher.rs, relm4/src/factory/builder.rs, relm4/src/factory/component_storage.rs, relm4/src/factory/handle.rs, relm4/src/factory/mod.rs
The overall goal of this PR is to make it possible to derive `Debug` for `Component` impls that have a `Controller` in them. This is accomplished by implementing `Debug` for all types in the library, including the complex types that were explicitly left unimplemented. This also involved relaxing the `Debug` bounds on `Sender` and `Receiver`, which weren't actually required.
Additionally, `Debug` is derived for the `Widgets` struct produced by the macro to make the new bounds easier to satisfy.
=> Implement `Debug` for all public types

relm4/src/factory/widgets/mod.rs, relm4/src/lib.rs
Fixes #171, which allows building the documentation with a stable compiler.
This will require changing the documentation build process to pass `--cfg dox` as a rustdoc argument.
=> only use `doc(cfg)` if `dox` cfg is present

relm4-macros/src/component/mod.rs, relm4-macros/tests/simple.rs
Looks like #169 was partially reverted by the merge of the new macro code. Re-added the derive and added a test.
=> derive Debug for Widgets struct

relm4-macros/src/widgets/parse_util.rs
A workaround for syn because some functions are not considered as public API (see: https://github.com/dtolnay/syn/issues/1190).
=> Workaround for syn's public API

relm4-macros/Cargo.toml, relm4-macros/src/attrs.rs, relm4-macros/src/component/mod.rs, relm4-macros/src/component/token_streams.rs, relm4-macros/src/factory/inject_view_code.rs, relm4-macros/src/factory/mod.rs, relm4-macros/src/lib.rs, relm4-macros/src/menu/gen.rs, relm4-macros/src/util.rs, relm4-macros/src/view.rs, relm4-macros/src/widgets/gen/assign/assign_property.rs, relm4-macros/src/widgets/gen/assign/conditional_widget.rs, relm4-macros/src/widgets/gen/assign/mod.rs, relm4-macros/src/widgets/gen/assign/properties.rs, relm4-macros/src/widgets/gen/assign/widgets.rs, relm4-macros/src/widgets/gen/conditional_init.rs, relm4-macros/src/widgets/gen/connect_signals.rs, relm4-macros/src/widgets/gen/init.rs, relm4-macros/src/widgets/gen/struct_fields.rs, relm4-macros/src/widgets/gen/update_view.rs, relm4-macros/src/widgets/gen/util/property_name.rs, relm4-macros/src/widgets/parse/top_level_widget.rs, relm4-macros/src/widgets/parse_util.rs
"relm4_path" was added as feature to specify the path of the Relm4 crate used by relm4-macros. To keep macro hygiene, all paths started with `::relm4` to avoid that someone would have an item in scope that had the name "relm4" but wasn't the actual crate. That required passing the path to a lot of code generation functions and in general wasn't worth the effort. There's simply no plausible situation in which you had "relm4" in the scope and it's not the crate.
The only situation would be a re-export, which made this so complicated in the first place. If you had a crate that re-exported Relm4, the macro wouldn't work because it uses `use ::relm4::item`. Now, with `use relm4::item` the generated code works in every scope that has the Relm4 crate included.
=> macros: Remove relm4_path

examples/Cargo.toml, examples/non_blocking_async.rs, relm4/src/worker.rs
This PR changes `WorkerController` and `WorkerHandle` to use the `Worker` impl instead of the input and output types directly, which reads a bit nicer (`WorkerController<MyWorker>` instead of `WorkerController<MyWorkerMsg>`.
This commit also ports over the non-blocking-async example.
=> tweak `WorkerController` and port non-blocking-async example

relm4/src/worker.rs
The current behavior will cause all updates to be serialized in the order they are received, instead of interleaving them. The change in behavior can be seen in the non-blocking async example by clicking the button three times.
=> spawn worker updates instead of awaiting them

relm4-macros/src/lib.rs, relm4-macros/tests/simple.rs, relm4/Cargo.toml, relm4/src/component/builder.rs, relm4/src/component/traits.rs, relm4/src/factory/builder.rs, relm4/src/factory/traits.rs
Fixes #198.
Only logs `update_with_view` and `update_view_with_cmd`, expecting more events to be added in the future. Most importantly, this adds `Debug` bounds to `Input` and `Output` so that the breaking changes are in early.
=> emit tracing logs on received inputs

examples/non_blocking_async.rs, examples/worker.rs, relm4/src/app.rs, relm4/src/worker.rs
Changes: 
+ Make workers a subset of `SimpleComponent`
+ For components without widgets and `Send` impls for messages (e. g. `Worker` trait impls), allow running them on their own thread
+ Make workers sync again as async stuff (previously AsyncWorker) is already done much better by using commands
TODO:
=> Use Component trait for Worker

examples/factory.rs, examples/grid_factory.rs, examples/libadwaita/tab_factory.rs, examples/libadwaita/tab_game.rs, relm4-macros/src/factory/inject_view_code.rs, relm4-macros/src/factory/mod.rs, relm4/src/factory/builder.rs, relm4/src/factory/collections/vec_deque.rs, relm4/src/factory/component_storage.rs, relm4/src/factory/handle.rs, relm4/src/factory/mod.rs, relm4/src/factory/traits.rs
`FactoryComponent` uses generics to define `ParentWidget` and `ParentMsg`. This way, a single type can have multiple component implementations for different container types. But it comes with a tradeoff: generic arguments must be specified for most factory types. For example, `FactoryVecDeque<gtk::Box, Counter, AppMsg>` or `FactoryComponentSender<gtk::Box, AppMsg, Self>`.
This PR replaces generics with associated types, removing the need to specify generic arguments: `FactoryVecDeque<Counter>`, `FactoryComponentSender<Self>`.
It would still be possible to provide multiple implementations, if the type that implements `FactoryComponent` is itself generic.
=> Do not use generics in `FactoryComponent`

relm4/src/component/sender.rs
Makes `sender.command()` take `FnOnce` to avoid issues with moving values. Often you want to move a value into the closures and then into the async block, but that doesn't work with `Fn` because it might be called multiple times.
Example:
```rust
// Make sure password is owned to move it into the async block
let password = self.password.clone();
sender.command(move |out, shutdown| {
shutdown.register(async move {
// Only works after the patch because Fn might be called multiple times.
use_password(password).await;
}).drop_on_shutdown()
});
```
@mmstick can you review since you wrote this part of the code originally?
=> Make commands use FnOnce

examples/Cargo.toml, examples/to_do.rs, examples/tracker.rs
cc #100 
This PR also adds a delete button to the to_do example, which helps demonstrate internal communication in the factory component versus communication with the parent.
=> Port tracker and to_do examples to 0.5

Cargo.toml, examples/Cargo.toml, examples/relm4-components/Cargo.toml, examples/relm4-components/file_dialogs.rs, relm4-components/src/lib.rs, relm4-components/src/open_dialog.rs, relm4-components/src/save_dialog.rs, relm4-components/src/traits.rs, relm4/src/component/builder.rs
Related to #101.
- Port `OpenDialog` and `SaveDialog` to the next version or relm4.
- ~~Dialogs use a non-native file chooser.~~
-  See #143 
- Added a new example, featuring a simple text editor.
- Added Default settings for both dialogs.
- Button labels now use `String` instead of `&'static str`, which allows creating them dynamically at runtime.  
- Support for selecting folders.
- Support for multi selection.
=> Port file dialogs to 0.5

CHANGES.md, relm4/src/app.rs, relm4/src/lib.rs
Adds a `main_application()` method to receiver the `gtk/adw::Application` used internally by `RelmApp`.
=> Add getter for global application

CHANGES.md, relm4/src/factory/collections/vec_deque.rs
Gonna need it myself anyway. Fixes #257.
\* On an unrelated note, compiling `libadwaita-examples` results in a memory leak and a crash on my system...
=> Return a clone of the `DynamicIndex` after inserting into a factory

relm4-macros/src/component/mod.rs, relm4-macros/src/factory/mod.rs, relm4-macros/tests/ui/compile-fail/pre-view-return.rs, relm4-macros/tests/ui/compile-fail/pre-view-return.stderr
Add IIFE guards around the whole `update_view` block of the macro codegen to prevent early returns in `pre_view`.
Fixes #256
=> macros: Prevent early returns in pre_view

CHANGES.md, examples/components.rs, examples/menu.rs, relm4/src/app.rs, relm4/src/lib.rs
This PR contains a few improvements to how we handle GTK application types. Chiefly, it replaces the `Application` type alias with `IsA<gtk::Application>`, because `adw::Application` is a subclass of `gtk::Application`. This, along with a change to not manually initialize GTK or libadwaita, allows users to enable the libadwaita feature without being forced into using `adw::Application` or libadwaita styles. Lastly, this PR makes the `app` field on `RelmApp` private, because it can be accessed through `relm4::main_application`.
Fixes #255.
=> always use `gtk::Application` in public APIs

CHANGES.md, examples/factory.rs, examples/grid_factory.rs, examples/libadwaita/tab_factory.rs, examples/libadwaita/tab_game.rs, examples/to_do.rs, relm4/src/factory/builder.rs, relm4/src/factory/collections/vec_deque.rs, relm4/src/factory/component_storage.rs, relm4/src/factory/traits.rs
This PR renames `ParentMsg` to `ParentInput` and `output_to_parent_msg` to `output_to_parent_input` to bring the `FactoryComponent` naming more in-line with `Component`.
=> rename `ParentMsg` to `ParentInput`

CHANGES.md, examples/relm4-components/.gitignore, examples/relm4-components/Cargo.toml, examples/relm4-components/open_button.rs, relm4-components/src/lib.rs, relm4-components/src/open_button/factory.rs, relm4-components/src/open_button/mod.rs, relm4/src/factory/collections/vec_deque.rs
Updates the `OpenButton` component to 0.5 syntax and adds the "open_button" example back.
cc #100.
=> Port `OpenButton` component to 0.5 syntax

CHANGES.md, examples/simple.rs, examples/to_do.rs, relm4/src/lib.rs, relm4/src/prelude.rs
This PR adds a prelude module that contains the traits and types that are needed to implement a component. This helps reduce the import boilerplate required to implement a new component. Two examples are modified to demonstrate the benefit.
I purposely tried to keep it pretty conservative. Right now it only contains traits, the types required to implement the methods on those traits, and the gtk crates. It might be helpful to include `RelmApp` or `FactoryVecDeque`, but those are left out for now.
=> add a prelude module

CHANGES.md, relm4/src/extensions/container.rs, relm4/src/extensions/set_child.rs
Append children for `gtk::Dialog` to its content area instead of using `set_child`
=> set_child() vs content_area().append() for gtk::Dialog

CHANGES.md, examples/macro_reference.rs, relm4-macros/src/lib.rs, relm4-macros/src/util.rs, relm4-macros/src/widgets/gen/assign/assign_property.rs, relm4-macros/src/widgets/mod.rs, relm4-macros/src/widgets/parse/assign_property.rs, relm4-macros/src/widgets/parse/attributes.rs, relm4-macros/src/widgets/span/attr.rs, relm4-macros/tests/ui/compile-fail/bad_impl.rs, relm4-macros/tests/ui/compile-fail/bad_impl.stderr
Adds a `#[chain(method())]` attribute to work with types returned by property assignments. For example, `bind_property()` returns a builder that needs a call to `build()` in order to take effect.
=> Add chain attr to properties

CHANGES.md, relm4-macros/src/component/inject_view_code.rs, relm4-macros/src/component/mod.rs, relm4-macros/src/factory/inject_view_code.rs, relm4-macros/src/factory/mod.rs, relm4-macros/src/lib.rs, relm4-macros/src/visitors.rs, relm4-macros/src/widgets/gen/conditional_init.rs, relm4-macros/src/widgets/gen/update_view.rs, relm4-macros/src/widgets/gen/util/if_branch.rs, relm4-macros/src/widgets/parse/widget_func.rs
When adding #![warn(clippy::pedantic)] to the code, there were a few lints that were easy to solve. A few of the functions were called by value when they could have also been called by reference instead. I changed it so the API changed, which I mentioned in the CHANGES.md file.
I solved the following lints:
Added semicolon
https://rust-lang.github.io/rust-clippy/master/index.html#semicolon_if_nothing_returned
Passed by reference instead of by value
https://rust-lang.github.io/rust-clippy/master/index.html#needless_pass_by_value
Removed borrow
https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
Unresolved:
https://rust-lang.github.io/rust-clippy/master/index.html#too_many_lines
https://rust-lang.github.io/rust-clippy/master/index.html#let_underscore_drop
=> Changed methods to take refs instead of values in relm4-macros

relm4-components/src/open_button/mod.rs
When adding #![warn(clippy::pedantic)] to the code, there was one lint that was easy to solve:
Changed method from flat_map to filter_map
https://rust-lang.github.io/rust-clippy/master/index.html#flat_map_option
Unresolved:
https://rust-lang.github.io/rust-clippy/master/index.html#used_underscore_binding
https://rust-lang.github.io/rust-clippy/master/index.html#module_name_repetitions
https://rust-lang.github.io/rust-clippy/master/index.html#let_underscore_drop
https://rust-lang.github.io/rust-clippy/master/index.html#cast_possible_truncation
https://rust-lang.github.io/rust-clippy/master/index.html#cast_possible_wrap
=> Changed method from flat_map to filter_map in relm4-components

CHANGES.md, relm4/src/extensions/mod.rs, relm4/src/extensions/set_child.rs
Implement `ContainerChild` and `RelmSetChildExt` for `adw::ToastOverlay`
=> Add ToastOverlay to ContainerChild + SetChildExt

CHANGES.md, examples/libadwaita/Cargo.toml, examples/libadwaita/leaflet_sidebar.rs
This PR creates a new example that uses `adw::Leaflet` for a responsive sidebar.
=> add responsive sidebar example using adw::Leaflet

CHANGES.md, README.md, relm4-components/Cargo.toml, relm4/Cargo.toml
This adds the `dox` feature so that docs.rs can activate it and build the docs without having all dependencies. See issue https://github.com/Relm4/Relm4/issues/292 for a detailed description.
=> Added dox feature

.github/workflows/rust.yml, CHANGES.md, README.md, relm4-components/Cargo.toml, relm4/Cargo.toml
- Use [multiple locations](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-locations) to simplify `cargo publish`
- Exclude libpanel until it's compatible with the other gtk-rs crates
- Disable the nightly workflow that has been causing problems for weeks due to a regression in the Rust compiler
=> Improve deps

.github/workflows/rust.yml
Upgrades the CI toolchain setup to use dtolnay/rust-toolchain.
Fixes #320.
=> migrate to dtolnay/rust-toolchain

.github/workflows/rust.yml, relm4/Cargo.toml
Now that libpanel-rs has a 0.1 release, we can re-enable the library and feature.
=> re-enable libpanel

.github/dependabot.yml
Dependabot can check the versions of the Github Actions. This will help keep them updated.
I also could not find any opened PRs from dependabot, even though I created a pull request to update criterion a few days ago. This leads me to believe dependabot is not working as expected. I pointed dependabot to the folders containing the Cargo.toml files, which should fix it.
=> Have dependabot check the Github Actions

.github/workflows/rust.yml, relm4-macros/src/widgets/gen/util/widget_func.rs, relm4-macros/src/widgets/parse/attributes.rs
All Actions from actions-rs seem to no longer be maintained. This also applies to actions-rs/cargo. It can just be replaced by the cargo command. I also fixed a small clippy lint to fix the workflows
=> Remove actions rs

CHANGES.md, examples/factory.rs, relm4/src/factory/builder.rs, relm4/src/factory/data_guard.rs, relm4/src/factory/traits.rs, relm4/src/shutdown/attached.rs, relm4/src/shutdown/mod.rs, relm4/src/shutdown/receiver.rs, relm4/src/shutdown/sender.rs
The previous way this was handled was pretty bad actually.
First of all, there were two ways to drop the runtime: When the `FactoryHandle` was dropped or when the root widget was dropped. The problem: the root widget cannot be dropped because it's stored in the `FactoryHandle` and likely also in the runtime itself. This is kind of a cyclic reference problem, the runtime stops when the root is dropped while the runtime keeps the root alive.
To solve this, `FactoryHandle` is now the only point that drops the runtime.
It also calls the `shutdown` method, so there's no weird sending of messages to the runtime to let it shutdown itself, instead it is properly stopped from outside (which also fixes all potential synchronization issues because we don't know how long it takes for messages to …
=> core: Fix shutdown in factories

relm4/src/component/async/traits.rs, relm4/src/component/sync/traits.rs
This PR updates the `Component` documentation to remove some incorrect information and expand on some gotchas.
=> clarify component documentation

CHANGES.md, examples/drawing.rs, examples/libadwaita/tab_game.rs, examples/message_stream.rs, examples/non_blocking_async.rs, examples/progress.rs, examples/settings_list.rs, examples/simple_async.rs, examples/transient_dialog.rs, relm4-components/src/simple_combo_box.rs, relm4/src/component/async/builder.rs, relm4/src/component/async/traits.rs, relm4/src/component/sync/builder.rs, relm4/src/component/sync/stream.rs, relm4/src/component/sync/traits.rs, relm4/src/component/worker.rs
Currently, the root is only passed to the `init()` function but not available later. Therefore, if you want to create a dialog as response to a message, you can't simply call `set_transient_for()`. As a workaround, you can use `update_with_view()` which isn't a great solution.
This PR adds the root as a parameter of `update()` and `update_cmd()` for `Component` and `AsyncComponent`.
All sub-traits like `SimpleComponent` are not affected.
This makes it easier to use dialogs the way they are intended to be used by the GTK developers (a window that waits for a response and is destroyed afterwards).
The changes in the "message_stream" example show how this helps with creating dialogs.
=> core: Pass root to update and update_cmd

relm4-components/src/lib.rs, relm4-macros/src/lib.rs, relm4/src/lib.rs
As mentioned in https://github.com/Relm4/Relm4/issues/292, in order to have the same content in the docs regardless of where they are built, the preprocessed doc headers need to be moved to the source. I moved the collection of links to the source. There are two downsides
- I am not sure it is possible to add the timestamp of the creation to it so I left it out
- The links point to the nightly versions of the other libraries ([gtk4-rs](https://gtk-rs.org/gtk4-rs/git/docs) | [gtk-rs-core](https://gtk-rs.org/gtk-rs-core/git/docs) | [libadwaita-rs](https://world.pages.gitlab.gnome.org/Rust/libadwaita-rs/git/docs/libadwaita) | [libpanel-rs](https://world.pages.gitlab.gnome.org/Rust/libpanel-rs/git/docs/libpanel))
- The link to the book goes to the stable version https://relm4.org/book/stable/ …
=> Move the pre-proccessed doc headers into source

CHANGES.md, relm4-macros/src/lib.rs, relm4-macros/src/menu/gen.rs, relm4-macros/src/menu/mod.rs
=> macros: Allow expressions for menu entry names

CHANGES.md, examples/tracker.rs, relm4/src/app.rs, relm4/src/lib.rs
Fixes #364
Also, `set_global_css()` now takes  `&str` instead of `&[u8]` which should make it easier to use with regular string literals and CSS should be valid UTF-8 anyway.
=> Fix app init

CHANGES.md, relm4/src/channel/component.rs
Earlier, this struct was being leaked due to the implementation of Deref. However, since the struct was never actually exported, documentation was not being generated for it's methods.
This commit just makes the struct private and instead creates wrapper functions over it. This is typically whats done in Rust std.
Signed-off-by: Ayush Singh <ayushsingh1325@gmail.com>
=> Prevent leaking CommandSenderInner struct

CHANGES.md, relm4/src/factory/async/collections/vec_deque.rs, relm4/src/factory/sync/collections/vec_deque.rs
In order to send a message to all elements in `FactoryVecDeque`, it was previously necessary to manually cycle through all the indices (from 0 to `len()`) and send message to each element, one by one, using an existing `send` method. This new method makes this process cleaner and safer by avoiding the need to use panic-prone indices.
=> Add method `broadcast` to `FactoryVecDeque`

CHANGES.md, examples/Cargo.toml, examples/factory_async.rs, examples/simple_async.rs, relm4/src/app.rs
This PR adds a hack also used by async-std to archive compatibility with tokio. More or less this just means entering the tokio context before running the application. 
@edfloreshz can you maybe test this with Done? This should remove the need to wrap tokio-depndant futures into `relm4::spawn()`.
=> core: Support tokio on local futures

CHANGES.md, relm4/src/factory/async/collections/mod.rs, relm4/src/factory/async/collections/vec_deque.rs, relm4/src/factory/sync/collections/mod.rs, relm4/src/factory/sync/collections/vec_deque.rs
Previously, the UID of a factory collection could overflow when there had been enough changes to a `FactoryVecDeque` to go over the 16-bit integer limit. The type of the UID has been bumped from a `u16` to a `usize`, and every time `clear` is called, the UID is reset to 1.
=> core: Fix crash caused by UID overflow with very large or frequently changing factories

CHANGES.md, relm4-macros/src/component/mod.rs
The code generated by macro requires importing `ComponentSender`:
```
error[E0412]: cannot find type `ComponentSender` in this scope
--> src/application/widget.rs:14:1
|
14 | #[relm4::component(pub)]
| ^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
|
= note: this error originates in the attribute macro `relm4::component` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this struct
|
1  | use relm4::ComponentSender;
|
For more information about this error, try `rustc --explain E0412`.
```
=> macros: Use type fullname

publish.sh
This will finally enable scraping of examples on docs.rs and make the publish process easier.
The script renames the Cargo.toml file of the examples so `cargo publish` doesn't ignore the examples because it thinks it's another crate.
=> all: Add script for publishing the crates

CHANGES.md, README.md, examples/settings_list.rs, relm4-components/Cargo.toml, relm4-components/README.md, relm4-components/src/lib.rs, relm4-macros/Cargo.toml, relm4-macros/README.md, relm4-macros/src/lib.rs, relm4/Cargo.toml, relm4/src/lib.rs
This will make crates.io link to the docs hosted on docs.rs.
=> Change the link of the docs of all crates to docs.rs

CHANGES.md, examples/factory.rs, examples/factory_async.rs, relm4/src/factory/async/collections/vec_deque.rs, relm4/src/factory/async/traits.rs, relm4/src/factory/sync/collections/vec_deque.rs, relm4/src/factory/sync/traits.rs
I've noticed a regression that makes the application freeze after quitting. This might fix it and is the correct behavior anyway.
=> core: Fix drop impl of factories

CHANGES.md, relm4-macros/src/component/mod.rs, relm4-macros/src/factory/mod.rs, relm4-macros/src/view.rs, relm4-macros/src/widget_template.rs, relm4-macros/src/widgets/gen/assign/assign_property.rs, relm4-macros/src/widgets/gen/assign/mod.rs, relm4-macros/src/widgets/gen/conditional_init.rs, relm4-macros/src/widgets/gen/update_view.rs
Fixes #418
0.5 brings a new feature with the macro to block signal handlers when assigning properties. This was made possible by generating the signal handlers first and then at each property update with a `#[block_handler(handler_name)]`, the signal handler would be temporarily blocked. 
However, this is not great for initializing properties because even on initialization a signal it fired sometimes unless you use the `block_handler` attribute. With this PR, the old order of code generation is restored: First assign properties, then generate signal handlers. The `block_handler` attribute now only affects property updates done with either `#[watch]` or `#[track]` because initialization won't cause any events anyway.
@imsamuka can you test your code against this branch? I think this should …
=> macros: Fix ordering in codegen

CHANGES.md, examples/entry.rs, examples/factory.rs, examples/factory_async.rs, examples/grid_factory.rs, examples/to_do.rs, relm4-components/src/open_button/factory.rs, relm4-macros/src/lib.rs, relm4/src/factory/async/component_storage.rs, relm4/src/factory/async/traits.rs, relm4/src/factory/sync/component_storage.rs, relm4/src/factory/sync/traits.rs
This PR renames `FactoryComponent`'s and `AsyncFactoryComponent`'s method `output_to_parent_input` to a more intuitive expressive name `forward_to_parent`
=> Rename factory component traits `output_to_parent_input` method to `forward_to_parent`

examples/components.rs, examples/factory_hash_map.rs, examples/macro_reference.rs, examples/message_broker.rs, examples/message_stream.rs, examples/progress.rs, examples/transient_dialog.rs, relm4-components/examples/file_dialogs.rs, relm4-components/src/lib.rs, relm4-components/src/web_image.rs, relm4/src/actions/mod.rs, relm4/src/app.rs, relm4/src/extensions/container.rs, relm4/src/extensions/mod.rs, relm4/src/extensions/remove.rs, relm4/src/extensions/widget_ext.rs, relm4/src/factory/sync/collections/hashmap.rs, relm4/src/lib.rs
There are three categories of deprecation:
1. Easy to fix: Simple things like `show()` -> `set_visible(true)`, apply changes immediately
2. Trait impls: We shouldn't remove trait impls for deprecated types because some might still use those types
3. Only 4.10 replacements available: Ignore those entirely, we don't want Relm4 to lift its GTK4 requirement to the recent 4.10 release (which might take years to land in some distros).
=> all: Ignore most GTK 4.10 deprecations

CHANGES.md, relm4/src/factory/sync/collections/vec_deque.rs
This PR replaces `FactoryVecDeque`'s associated function `from_vec` which creates a `FactoryVecDeque` from a `Vec` with a more universal `from_iter` which creates a `FactoryVecDeque` from any type implementing `IntoIterator`
=> Replace `FactoryVecDeque`'s associated function `from_vec` with `from_iter`

CHANGES.md, relm4/src/extensions/mod.rs, relm4/src/extensions/set_child.rs
This PR adds `RelmSetChildExt` implementation for `gtk::AspectFrame`
=> Implement `RelmSetChildExt` for `gtk::AspectFrame`

CHANGES.md, relm4-macros/src/util.rs, relm4-macros/src/visitors.rs, relm4-macros/tests/ui/compile-fail/init-identifers.rs, relm4-macros/tests/ui/compile-fail/init-identifers.stderr
This PR improves the error messages when attempting to use a non-identifier pattern for certain init function arguments. It also removes some duplication of that error handling.
Previous:
```
error: unable to determine root name
--> tests/ui/compile-fail/init-identifers.rs:18:9
|
18 |         (a, b): &Self::Root,
|         ^^^^^^^^^^^^^^^^^^^
error: unable to determine sender name
--> tests/ui/compile-fail/init-identifers.rs:19:9
|
19 |         _: ComponentSender<Self>,
|         ^^^^^^^^^^^^^^^^^^^^^^^^
error: unable to determine root name
--> tests/ui/compile-fail/init-identifers.rs:42:5
|
42 |     fn init() -> ComponentParts<Self> {
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error: unable to determine sender name
--> tests/ui/compile-fail/init-identifers.rs:42:5
|
42 |     fn init() -> …
```
=> improve init parameter error handling

examples/settings_list.rs
Fixes #458
Starting with version 0.5, dropping the `Controller` defaults to destroying the runtime. This caused a sender error in an example because the receiving end was dropped together with the component's runtime. With this PR, this oversight will be fixed.
=> examples: Fix sending to dropped runtime

CHANGES.md, relm4/src/extensions/mod.rs, relm4/src/extensions/remove.rs
- Implemented `RelmRemoveExt` for `adw::ExpanderRow`. 
- Implemented `ContainerChild` for `adw::ExpanderRow`.
- `adw::ExpanderRow` can now be loaded asynchronously.
=> Improvements to ExpanderRow

CHANGES.md, examples/libadwaita/tab_factory.rs, examples/libadwaita/tab_game.rs
Fix the compilation of the `examples/libadwaita/tab_game.rs` and `examples/libadwaita/tab_factory.rs`.
Maybe their compilation should be added to the CI?
=> Fix compilation of tab examples

CHANGES.md, examples/libadwaita/leaflet_sidebar.rs
The libadwaita sidebar/leaflet example did not include a separator, while most sidebar will want one.
There is however a subtlety when it comes to adding a separator, as it needs to be wrapped in a `LeafletPage` with the `navigatable` property set to false. However `LeafletPage` is created automatically by the leaflet and cannot be created manually.
There is therefore a bit of a subtlety is required to get access to the generated `LeafletPage` and set it to not navigatable.
It took me some time and some help from the GTK-RS channel to get how to do it, I think having it in the example will help.
=> Add a separator to the leaflet example

examples/typed_column_view.rs, relm4/src/typed_list_view/column_view.rs
YOLO implementation of typed wrapper for gtk::ColumnView. Largely based on TypedListView, but modified to have per-column factories as required by ColumnView API.
=> Implement TypedColumnView

relm4-macros/tests/returned_widgets.rs
Hi there, while trying to use returned widgets with a widget generated by a container, I could not find any docs and tried fiddling with the tests (as they are a more up-to date than the docs) to make it work. Maybe they can also work as docs?
=> ci(macros): Add tests for returned widgets without builders

CHANGES.md, relm4-macros/src/widgets/gen/assign/conditional_widget.rs, relm4-macros/src/widgets/gen/assign/mod.rs, relm4-macros/src/widgets/gen/assign/widgets.rs, relm4-macros/src/widgets/gen/conditional_init.rs, relm4-macros/src/widgets/gen/update_view.rs, relm4-macros/src/widgets/gen/util/property_name.rs, relm4-macros/src/widgets/gen/util/widget_func.rs, relm4-macros/tests/widget_template_nested_child.rs
Fixes #505 
Adds support for a macro syntax to access nested template children.
For example, according to #504, you might have a template `SettingsPage` with a button  `btn_dark_mode` and another template `MainWidget` that includes an instance of `SettingsPage` with name `settings_page`.
With this PR, it will be possible to access the `btn_dark_mode` by using it's path `settings_page.btn_dark_mode`.
```rust
adw::Window {
// ...
#[template]
MainWidget {
// Access MainWidget->SettingsPage->btn_dark_mode like this:
#[template_child] 
settings_page.btn_dark_mode {
connect_clicked => Message::DarkMode,
},
},
}
```
@eminfedar could you please test this PR with your code?
=> macros: Add support for accessing nested template children

CHANGES.md, examples/widget_template.rs, relm4-macros/src/widget_template.rs, relm4/src/app.rs, relm4/src/extensions/mod.rs
Fixes widget templates as root of the component used in `RelmApp`.
=> core: Allow widget templates as root of RelmApp

CHANGES.md, examples/macro_reference.rs, relm4-macros/src/widgets/parse/match_arm.rs
=> macros: Allow trailing commas in the last match arm

CHANGES.md, relm4-components/Cargo.toml, relm4-components/examples/adw_combo_row.rs, relm4-components/src/lib.rs, relm4-components/src/simple_adw_combo_row.rs
This PR adds:
- A `SimpleComboRow` component, as an easy to use wrapper around `adw::ComboRow`, similar to the existing `SimpleComboBox`
- Examples for `SimpleComboBox` and `SimpleComboRow`
The examples are a bit raw, I can make them a bit prettier if necessary.
=> Add a `SimpleComboRow` helper for `adw::ComboRow`

CHANGES.md, relm4-components/examples/combo_box.rs
I found it not so easy to start using `SimpleComboBox` in my project (the book doesn't seem to explain much about injecting components into the view, the only examples I found were about dialogs, i.e., `#[local_ref]` is not really explained there).
So I created an example how to use it.
=> Add an example how to use SimpleComboBox

CHANGES.md, relm4-macros/src/widget_template.rs, relm4-macros/src/widgets/gen/init.rs, relm4-macros/src/widgets/gen/util/widget_func.rs, relm4-macros/tests/widget_template.rs, relm4/src/extensions/mod.rs
Allow passing data to `WidgetTemplate::init()` to make widget templates more flexible.
Due to clever use of the macros, existing code should still compile just fine.
=> core: Add `Init` type to `WidgetTemplate`

.github/workflows/rust.yml
Parallelize the `cargo clippy` check by running it in its own GH Actions job.
This will speed up the build, and also allow `cargo test` to execute even if Clippy fails, allowing us to see any test errors in addition to Clippy errors.
=> Run cargo clippy check in a parallel CI job

CHANGES.md, relm4/src/channel/component.rs
Return the `Result` object from `FactorySender#output`, instead of silently unwrapping it. This allows app developers to handle the `Result` as they wish (rather than it crashing the app if no handler function is attached).
This brings the signature of this `output` method into line with the `ComponentSender` and `AsyncComponentSender`.
=> Return Result from `FactorySender#output` method

examples/factory.rs, examples/grid_factory.rs, relm4-macros/src/lib.rs
I noticed a couple of the examples stopped compiling with the latest change in 828c940. This hotfix should make the build work again.
=> Hotfix: make factory and grid_factory examples work again

CHANGES.md, relm4/src/extensions/container.rs, relm4/src/extensions/mod.rs, relm4/src/extensions/set_child.rs
Implement Relm traits for `NavigationView` and `NavigationPage` introduced in libadwaita v1.4.
(I did not touch `NavigationSplitView`)
This doesn't close any issue, as far as I know, but makes working with the new widgets easier. I've almost opened an issue but decided to try to fix the problem myself instead. This is my first time working with this code base so please let me know if there are any issues. I tried out the changes in a small test application and didn't encounter any issues.
=> Implement traits to make working with the new adwaita NavigationView easier

CHANGES.md, examples/entry.rs, examples/factory.rs, examples/factory_async.rs, examples/factory_hash_map.rs, examples/grid_factory.rs, examples/state_management.rs, examples/to_do.rs, relm4-components/src/open_button/factory.rs, relm4-components/src/open_button/mod.rs, relm4/src/binding/mod.rs, relm4/src/channel/component.rs, relm4/src/component/async/connector.rs, relm4/src/component/sync/connector.rs, relm4/src/component/worker.rs, relm4/src/factory/async/builder.rs, relm4/src/factory/async/collections/mod.rs, relm4/src/factory/async/collections/vec_deque.rs, relm4/src/factory/async/component_storage.rs, relm4/src/factory/async/mod.rs, relm4/src/factory/async/traits.rs, relm4/src/factory/mod.rs, relm4/src/factory/sync/collections/hashmap.rs, relm4/src/factory/sync/collections/mod.rs, relm4/src/factory/sync/collections/vec_deque.rs, relm4/src/factory/sync/mod.rs, relm4/src/runtime_util.rs
[See changelog](https://github.com/Relm4/Relm4/compare/async-factory-builder?expand=1#diff-d975bf659606195d2165918f93e1cf680ef68ea3c9cab994f033705fea8238b2) + some minor cleanups
I think using `::builder().launch(arg)` is more natural then `::builder(arg).launch()`.
@chriskilding if you have time, can you have a look over the changes?
=> core: Add builder pattern for async factories

examples/libadwaita/tab_factory.rs, examples/libadwaita/tab_game.rs
Updates the libadwaita examples (specificially `tab_factory` and `tab_game`) to fix compiler errors.
Previously, the aforementioned libadwaita examples failed to compile, this fix allows the examples to work.
- [ ✓ ] cargo fmt
- [ ✓ ] cargo clippy
- [ ✓ ] cargo test
- [ ✓ ] updated CHANGES.md
=> fixes for adw::TabView examples

CHANGES.md, examples/libadwaita/Cargo.toml, examples/libadwaita/toast.rs
This PR adds an example for using an `adw::Toast`.
The current example looks pretty bad since I'm just figuring it out (which is why I wished there was already such an example and want to add my own). This PR is a much a PR to improve the examples as it is me asking for help to figure it out.
=> Add adw::Toast example

CHANGES.md, relm4/src/app.rs
Currently `RelmApp` does full components initialization in `gtk::Application::activate` signal handler. This is problematic for apps that needs to be able to run in the background, because they use `activate` signal to switch back to foreground. This PR moves the initialization to `startup` signal handler, and uses `activate` signal only for setting the main window visible.
This shouldn't change the behavior of any existing apps unless they used `gtk::Application::connect_startup` directly.
=> Move internal initialization to startup signal handler

CHANGES.md, relm4-components/examples/alert.rs, relm4-components/src/alert.rs
The `Alert` component from `relm4_components` previously didn't have the flexibility I needed for certain uses cases (as discussed in #575). This PR adds those changes.
I also added a `Default` implementation to aid in quickly creating new instances of `Alert` when a ton of configuration isn't desired (i.e. a title and single button, and then `..Default::default()` can be called instead of specifying everything else manually). I added documentation on how the `Default` implementation behaves as I currently don't have it using the `Default` values for all the struct's fields.
As part of my testing I also noticed that hitting the `Esc` key while an `Alert` dialog is open will make it unable to be shown again. I'm not sure what the best approach to fixing that is, but I thought I'd mention …
=> Increase flexibility of `Alert` component

CHANGES.md, examples/macro_reference.rs, relm4-macros/src/menu/gen.rs, relm4-macros/src/menu/parse.rs, relm4-macros/src/util.rs, relm4-macros/src/view.rs, relm4-macros/src/widget_template.rs, relm4-macros/src/widgets/gen/assign/assign_property.rs, relm4-macros/src/widgets/gen/conditional_init.rs, relm4-macros/src/widgets/gen/update_view.rs, relm4-macros/src/widgets/gen/util/if_branch.rs, relm4-macros/src/widgets/parse/conditional_widget.rs, relm4-macros/src/widgets/parse/if_branch.rs, relm4-macros/src/widgets/parse/returned_widget.rs, relm4-macros/src/widgets/parse_util.rs, relm4/src/binding/bindings.rs, relm4/src/factory/sync/collections/hashmap.rs, relm4/src/factory/widgets/libadwaita.rs, relm4/src/lib.rs
Fixes #532
@PJungkamp it seems like `mixed_site` would have been more correct in some cases, but it didn't cause the problem. The actual cause was that the span of the type (like `gtk::Box`) was used for the automatically generated ident (like `_gtk_box_1`), so it looked to clippy like it was added by the user. This behavior was initially added because I thought it might help with error reporting, but in the end it can only cause problems if the macro does something wrong.
Can you test if this fixes the problem for you?
=> macros: Improve codegen to prevent incorrect lints

CHANGES.md, examples/typed_column_view.rs, relm4/src/typed_view/column.rs
Adds `const bool`s to [`RelmColumn`](https://docs.rs/relm4/0.7.0-beta.2/relm4/typed_view/column/trait.RelmColumn.html) (and [`LabelColumn`](https://docs.rs/relm4/0.7.0-beta.2/relm4/typed_list_view/trait.LabelColumn.html)) that allow for setting the created columns to be resizeable, or to automatically expand.
Fixes #588
=> Column resize/expand functionality

CHANGES.md, relm4/Cargo.toml
This PR restores the libpanel feature and bumps it to 0.3, now there's been a new release.
=> bump libpanel to 0.3

CHANGES.md, examples/drawing.rs, relm4/src/drawing.rs
The dimensions reported by `width` and `height` on `DrawingHandler` were not scaled before. For those using those dimensions as size of the canvas, those numbers would be too large if a scaling factor other than 1 was used (for example for high DPI monitors). This is now fixed and two new methods are added that implement the old behavior.
=> core: Fix scaling of drawing coordinates

CHANGES.md, relm4/src/late_initialization.rs
Should fix #584
@nazar-pc can you try this branch? I'm not entirely sure whether this fixes your specific issue, but this change should be good in general.
With this PR, the following order of operations should start working:
1. Build a component
2. Call `transient_for` with a widget that is not connected yet
4. Add the widget to a window (or any other widget somehow connected to a window)
5. Return (from `init`, `update` or similar)
=> core: Improve late init callbacks after startup

CHANGES.md, relm4/src/app.rs
Usually, starting an already-running application again causes nothing to happen. However, with `allow_multiple_instances(true)`, the `NON_UNIQUE` flag is set, which makes it possible to run multiple instances of the application to run at the same time.
This should fix #396.
=> core: Add `allow_multiple_instances()` to `RelmApp`

CHANGES.md, examples/drop_sub_components.rs
Add Example for Sub-Components Drop Instead of Hide
This pull request introduces an example demonstrating how to make sub-components drop instead of merely hiding them.
Benefits:
* Dropping sub-components allows for better resource cleanup.
* When a component is removed from its parent, it no longer impacts the parent's size, unlike hiding which can leave hidden elements occupying space.
=> examples: drop sub-components instead of hiding

CHANGES.md, relm4-components/src/simple_combo_box.rs
Fixed panic that happens when calling get_active_elem() method on SimpleComboBox with empty variants.
- [+] cargo fmt
- [+] cargo clippy
- [+] cargo test
- [+] updated CHANGES.md
=> fixed panic on empty combo box

CHANGES.md, relm4/src/factory/async/builder.rs
As discussed on Matrix, this may cause panic if factory element is dropped too quickly
=> Ignore sending error if async component was dropped quickly

CHANGES.md, relm4-components/src/web_image.rs
`Image.new_from_pixbuf` was deprecated in 4.12: https://docs.gtk.org/gtk4/ctor.Image.new_from_pixbuf.html, this replaces it with `Texture::for_pixbuf` and `Image::from_paintable`
=> Replace deprecated `from_pixbuf` function

relm4/src/channel/component.rs
It is not possible to cancel synchronous commands.
=> Fix spawn_oneshot_command description

CHANGES.md, relm4/src/typed_view/column.rs, relm4/src/typed_view/grid.rs, relm4/src/typed_view/list.rs
This PR adds a `notify_filter_changed` function to all of the typed list abstractions. This is useful for making dynamic filters where the result may change between evaluations.
For example, I'm trying to make a text filter for a `TypedListView` where the user can filter items by entering text in a `SearchEntry`.
The filter looks like this:
```rust
model.list_view.add_filter({
let search_entry = widgets.search_entry.clone();
move |item| {
item
.name
.to_lowercase()
.contains(&search_entry.text().to_lowercase())
}
});
```
Currently to force this filter to update, you either have set it to inactive and then active, or completely re-add it to the list view on every input change.
With this function, I can simply notify that the filter has changed:
```rust
AppMsg::FilterChanged(filter) => {
if …
```
=> Add `notify_filter_changed` function to typed views

CHANGES.md, relm4/src/factory/sync/collections/vec_deque.rs
This PR addresses **Issue #600** by introducing a new `extend` method to the `FactoryVecDeque` struct. The method allows multiple components to be added efficiently in one call, improving the usability and performance when adding multiple elements to the deque.
- **New `extend` method**: The method takes an iterator of components and adds each component to the deque. It batches the changes within a `FactoryVecDequeGuard`, ensuring efficient rendering by accumulating all changes before they are processed.
Closes #600.
=> [feat:] implement extend method to add multiple components

relm4/src/factory/async/collections/vec_deque.rs, relm4/src/factory/sync/collections/hashmap.rs, relm4/src/factory/sync/collections/vec_deque.rs, relm4/src/runtime_util.rs, relm4/src/shared_state/state.rs
`cargo clippy` complaining about explicit lifetimes in code I haven't touched.
Happens both with current nightly (rustc 1.85.0-nightly (426d17342 2024-12-21))
and with current stable (rustc 1.83.0 (90b35a623 2024-11-26).
I'm also seeing some test failures as well, but only with stable.  So I don't expect this PR to pass CI.
=> Accept clippy fixes

CHANGES.md, examples/tracker.rs
The "tracker" example does not display the green "identical" background if the 2 randomly-chosen icons happen to be identical when the app is first initialized.    
Repro:
1. `$ cargo run --example tracker`
2. Visually compare the displayed icons.  If they are not identical:
a. exit the app
b. go to step 1.
Expect (when the initially displayed icons are identical):
-- the app window background should be green, indicating identical
Observe:
-- the app window background is not green
=> Display "identical" background if initial icons are the same.

CHANGES.md, relm4/src/typed_view/column.rs
I decided to use gettext for translations in my project. It uses a function for changing strings which is incompatible with the way column headers are determined. So i added a overwritable function in RelmColumn and LabelColumn that defaults to COLLUMN_NAME, so it doesn't break old code.
=> Added a overwritable function to change the header in RelmColumn

CHANGES.md, relm4/src/extensions/container.rs, relm4/src/extensions/mod.rs, relm4/src/extensions/remove.rs, relm4/src/extensions/set_child.rs
Allow adding children to libpanel's widgets.
=> Implement container traits for libpanel widgets

CHANGES.md, relm4/src/extensions/container.rs, relm4/src/extensions/mod.rs, relm4/src/extensions/remove.rs
Previously, in the `view` macro, `ListBox` and `FlowBox` only supported managing `ListBoxRow` and `FlowBoxChild`, respectively. Now, they accept any `Widget`, and gtk will automatically manage the appropriate children wrappers.
Fixes #587
=> Fix natural children management for ListBox and FlowBox in view macro

CHANGES.md, examples/typed_column_view.rs, examples/typed_grid_view.rs, examples/typed_list_view.rs, relm4/src/typed_view/column.rs, relm4/src/typed_view/grid.rs, relm4/src/typed_view/iterator.rs, relm4/src/typed_view/list.rs, relm4/src/typed_view/mod.rs
In my project I used a lot of iterating over `TypedListItem`s in the TypedViews. This makes them easier to traverse and makes the whole `Iterator` ecosystem usable for them.
=> add a iter method for iterating items in TypedGridView, TypedColumnView and TypedListView

examples/split_layout.rs, relm4/Cargo.toml
Add Libadwaita split layout example demonstrating AdwOverlaySplitView
Basic AdwOverlaySplitView implementation with:
- Collapsible sidebar (toggleable via button)
- Resizable sidebar width (toggles between 50px and 200px)
=> examples: Add AdwOverlaySplitView usage example
